------------------------------------------
--
-- Script:			04_LIPID_TREAT_CODES.sql
-- SAIL project:	1483 - Cardiovascular disease risk prediction and optimisation of risk factor management
--
-- About:			Lipid drug treatment codes for primary care data
-- Author:			Daniel King
------------------------------------------
--
--Drop Table
CALL FNC.DROP_IF_EXISTS('SAILW1483V.PHEN_DRUG_READ');
COMMIT;
------------------------------------------ 
--
-- Create Table
CREATE TABLE SAILW1483V.PHEN_DRUG_READ
(
	READ_CODE		VARCHAR(5),
	DESC			VARCHAR(198),
	READ_TYPE		VARCHAR(20),
	READ_CAT		VARCHAR(20)
) 
;
COMMIT;
------------------------------------------
--
--Insert into Table
INSERT INTO SAILW1483V.PHEN_DRUG_READ
(
--
--H2ANTAG
SELECT
	R.READ_CODE,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC,
	'H2ANTAG' AS READ_TYPE,
	'DRUG' AS READ_CAT
FROM
	SAILUKHDV.READ_CD_CV2_SCD R
WHERE
	READ_CODE LIKE 'a61%'
	OR READ_CODE LIKE 'a62%'
	OR READ_CODE LIKE 'a68%'
	OR READ_CODE LIKE 'a69%'
	OR READ_CODE LIKE 'a6d%'
UNION
--
--PPI
SELECT
	R.READ_CODE,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC,
	'PPI' AS READ_TYPE,
	'DRUG' AS READ_CAT
FROM
	SAILUKHDV.READ_CD_CV2_SCD R
WHERE
	READ_CODE LIKE 'a6b%'
	OR READ_CODE LIKE 'a6c%'
	OR READ_CODE LIKE 'a6e%'
	OR READ_CODE LIKE 'a6f%'
	OR READ_CODE LIKE 'a6h%'
UNION
--
--GLYCOSIDES
SELECT
	R.READ_CODE,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC,
	'GLUCOSIDE' AS READ_TYPE,
	'DRUG' AS READ_CAT
FROM
	SAILUKHDV.READ_CD_CV2_SCD R
WHERE
	READ_CODE LIKE 'b1%'
UNION
--
--THIAZIDE DIURETICS
SELECT
	R.READ_CODE,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC,
	'THIAZIDE' AS READ_TYPE,
	'DRUG' AS READ_CAT
FROM
	SAILUKHDV.READ_CD_CV2_SCD R
WHERE
	READ_CODE LIKE 'b2%'
UNION
--
--LOOP DIURETICS
SELECT
	R.READ_CODE,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC,
	'LOOP' AS READ_TYPE,
	'DRUG' AS READ_CAT
FROM
	SAILUKHDV.READ_CD_CV2_SCD R
WHERE
	READ_CODE LIKE 'b3%'
UNION
--
--POTSPARING DIURETICS
SELECT
	R.READ_CODE,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC,
	'POTSPARING' AS READ_TYPE,
	'DRUG' AS READ_CAT
FROM
	SAILUKHDV.READ_CD_CV2_SCD R
WHERE
	READ_CODE LIKE 'b41%'
	OR READ_CODE LIKE 'b42%'
	OR READ_CODE LIKE 'b44%'
UNION
--
--POT SPARING COMPOUND DIURTETICS
SELECT
	R.READ_CODE,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC,
	'POTSPARING COMPOUND' AS READ_TYPE,
	'DRUG' AS READ_CAT
FROM
	SAILUKHDV.READ_CD_CV2_SCD R
WHERE
	READ_CODE LIKE 'b5%'
UNION
--
--ALDOSTERONE ANTAG
SELECT
	R.READ_CODE,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC,
	'ALDO' AS READ_TYPE,
	'DRUG' AS READ_CAT
FROM
	SAILUKHDV.READ_CD_CV2_SCD R
WHERE
	READ_CODE LIKE 'b43%'
	OR READ_CODE LIKE 'b45%'
UNION
--
--VERAPMAIL-& DILTIAZEM
SELECT
	R.READ_CODE,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC,
	'SVT' AS READ_TYPE,
	'DRUG' AS READ_CAT
FROM
	SAILUKHDV.READ_CD_CV2_SCD R
WHERE
	READ_CODE LIKE 'bb3%'
	OR READ_CODE LIKE 'bl5%'
	OR READ_CODE LIKE 'blj%'
UNION
--
--BETABLOCKER
SELECT
	R.READ_CODE,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC,
	'BETA' AS READ_TYPE,
	'DRUG' AS READ_CAT
FROM
	SAILUKHDV.READ_CD_CV2_SCD R

WHERE READ_CODE LIKE 'bd1%'
	OR READ_CODE LIKE 'bd2%'
	OR READ_CODE LIKE 'bd3%'
	OR READ_CODE LIKE 'bd5%'
	OR READ_CODE LIKE 'bd6%'
	OR READ_CODE LIKE 'bd7%'
	OR READ_CODE LIKE 'bd8%'
	OR READ_CODE LIKE 'bda%'
	OR READ_CODE LIKE 'bdc%'
	OR READ_CODE LIKE 'bdd%'
	OR READ_CODE LIKE 'bdf%'
	OR READ_CODE LIKE 'bdj%'
	OR READ_CODE LIKE 'bdl%'
	OR READ_CODE LIKE 'bdm%'
	OR READ_CODE LIKE 'bdn5'
UNION
--
--VASODILATOR ANTIHYPERTENSIVES
SELECT
	R.READ_CODE,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC,
	'VASODILATOR' AS READ_TYPE,
	'DRUG' AS READ_CAT
FROM
	SAILUKHDV.READ_CD_CV2_SCD R
WHERE
	READ_CODE LIKE 'be%'
UNION
--
--CENTRAL-ANTIHYPERTENSIVES
SELECT
	R.READ_CODE,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC,
	'CENTRAL' AS READ_TYPE,
	'DRUG' AS READ_CAT
FROM
	SAILUKHDV.READ_CD_CV2_SCD R
WHERE
	READ_CODE LIKE 'bf%'
UNION
--
--ALFA BLOCKERS
SELECT
	R.READ_CODE,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC,
	'ALFA' AS READ_TYPE,
	'DRUG' AS READ_CAT
FROM
	SAILUKHDV.READ_CD_CV2_SCD R
WHERE
	READ_CODE LIKE 'bh%'
UNION
--
--ACEI/ARB/ENTRESTO
SELECT
	R.READ_CODE,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC,
	'ACE' AS READ_TYPE,
	'DRUG' AS READ_CAT
FROM
	SAILUKHDV.READ_CD_CV2_SCD R
WHERE
	READ_CODE LIKE 'bi%'
	OR READ_CODE LIKE 'bk3%'
	OR READ_CODE LIKE 'bk4%'
	OR READ_CODE LIKE 'bk5%'
	OR READ_CODE LIKE 'bk7%'
	OR READ_CODE LIKE 'bk8%'
	OR READ_CODE LIKE 'bkB%'
	OR READ_CODE LIKE 'bkC%'
	OR READ_CODE LIKE 'bkD%'
	OR READ_CODE LIKE 'bkH%'
	OR READ_CODE LIKE 'bkI%'
	OR READ_CODE LIKE 'bkL%'
UNION
--
--DIHYDROPYRIDINE CALCIUM CHANNEL
SELECT
	R.READ_CODE,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC,
	'AMLOD' AS READ_TYPE,
	'DRUG' AS READ_CAT
FROM
	SAILUKHDV.READ_CD_CV2_SCD R
WHERE
	READ_CODE LIKE 'bl7%'
	OR READ_CODE LIKE 'bl8%'
	OR READ_CODE LIKE 'blb%'
	OR READ_CODE LIKE 'blc%'
	OR READ_CODE LIKE 'ble%'
	OR READ_CODE LIKE 'blh%'
UNION
--
--PARENTERAL ANTICOAG
SELECT
	R.READ_CODE,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC,
	'PARENTERALANTICOAG' AS READ_TYPE,
	'DRUG' AS READ_CAT
FROM
	SAILUKHDV.READ_CD_CV2_SCD R
WHERE
	READ_CODE LIKE 'br%'
UNION
--
--VIT K-ANTICOAG
SELECT
	R.READ_CODE,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC,
	'VITK' AS READ_TYPE,
	'DRUG' AS READ_CAT
FROM
	SAILUKHDV.READ_CD_CV2_SCD R
WHERE
	READ_CODE LIKE 'bs1%'
	OR READ_CODE LIKE 'bs2%'
	OR READ_CODE LIKE 'bs3%'
UNION
--
--DOAC
SELECT
	R.READ_CODE,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC,
	'DOAC' AS READ_TYPE,
	'DRUG' AS READ_CAT
FROM
	SAILUKHDV.READ_CD_CV2_SCD R
WHERE
	READ_CODE LIKE 'bs4%'
	OR READ_CODE LIKE 'bs7%'
	OR READ_CODE LIKE 'bs6%'
	OR READ_CODE LIKE 'bs8%'
UNION
--
--ASPIRIN
SELECT
	R.READ_CODE,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC,
	'ASPIRIN' AS READ_TYPE,
	'DRUG' AS READ_CAT
FROM
	SAILUKHDV.READ_CD_CV2_SCD R
WHERE
	READ_CODE LIKE 'bu2%'
	OR READ_CODE = 'j111.'
UNION
--
--P2Y12-ANTIPLATELET
SELECT
	R.READ_CODE,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC,
	'P2Y12' AS READ_TYPE,
	'DRUG' AS READ_CAT
FROM
	SAILUKHDV.READ_CD_CV2_SCD R
WHERE
	READ_CODE LIKE 'buA%'
	OR READ_CODE LIKE 'buB%'
	OR READ_CODE LIKE 'bu5%'
UNION
--
--FIBRATE
SELECT
	R.READ_CODE,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC,
	'FIBRATE' AS READ_TYPE,
	'DRUG' AS READ_CAT
FROM
	SAILUKHDV.READ_CD_CV2_SCD R
WHERE
	READ_CODE LIKE 'bx1%'
	OR READ_CODE LIKE 'bx3%'
	OR READ_CODE LIKE 'bx6%'
	OR READ_CODE LIKE 'bxc%'
	OR READ_CODE LIKE 'bxf%'
UNION
--
--LOW-STATIN
SELECT
	R.READ_CODE,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC,
	'LOW_STATIN' AS READ_TYPE,
	'DRUG' AS READ_CAT
FROM
	SAILUKHDV.READ_CD_CV2_SCD R
WHERE
	READ_CODE IN ('bxd..','bxd1.','bxd2.','bxd3.','bxd4.','bxd5.','bxd6.','bxd7.',
	'bxd8.','bxd9.','bxdA.','bxdB.','bxdC.','bxdD.','bxdE.','bxdF.','bxdG.','bxdK.',
	'bxdu.','bxdv.','bxdz.','bxi1.','bxi2.','bxkx.','bxkw.','bxk4.','bxk1.','bxi4.','bxi5.')
	OR READ_CODE LIKE 'bxe%'
	OR READ_CODE LIKE 'bxg%'
	OR READ_CODE LIKE 'bxj%'	
UNION
--
---HIGH STATIN
SELECT
	R.READ_CODE,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC,
	'HIGH_STATIN' AS READ_TYPE,
	'DRUG' AS READ_CAT
FROM
	SAILUKHDV.READ_CD_CV2_SCD R
WHERE
	READ_CODE IN ('bxi3.','bxiz.','bxky.','bxkz.','bxi6.','bxi7.','bxk2.','bxk3.')
UNION
--
--INEGY (COMBINATION STATIN AND EZETIMIBE)
SELECT
	R.READ_CODE,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC,
	'INEGY' AS READ_TYPE,
	'DRUG' AS READ_CAT
FROM
	SAILUKHDV.READ_CD_CV2_SCD R
WHERE
	READ_CODE IN ('bxdw.','bxdx.','bxdy.','bxdJ.','bxdH.')
UNION
--
--FISH
SELECT
	R.READ_CODE,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC,
	'FISH' AS READ_TYPE,
	'DRUG' AS READ_CAT
FROM
	SAILUKHDV.READ_CD_CV2_SCD R
WHERE
	READ_CODE LIKE 'bxa%'
UNION
--
--OTHER LIPID
SELECT
	R.READ_CODE,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC,
	'OTHERLIPID' AS READ_TYPE,
	'DRUG' AS READ_CAT
FROM
	SAILUKHDV.READ_CD_CV2_SCD R
WHERE
	READ_CODE LIKE 'bx2%'
	OR READ_CODE LIKE 'bx4%'
	OR READ_CODE LIKE 'bx8%'
	OR READ_CODE LIKE 'bx9%'
	OR READ_CODE LIKE 'bxb%'
	OR READ_CODE LIKE 'bxb%'
	OR READ_CODE LIKE 'bxh%'
	OR READ_CODE LIKE 'bxm%'
	OR READ_CODE LIKE 'bxn%'
UNION
--
--EZETIMIBE
SELECT
	R.READ_CODE,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC,
	'EZETIMIBE' AS READ_TYPE,
	'DRUG' AS READ_CAT
FROM
	SAILUKHDV.READ_CD_CV2_SCD R
WHERE
	READ_CODE LIKE 'bxl%'
UNION
--
--INSULIN
SELECT
	R.READ_CODE,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC,
	'INSULIN' AS READ_TYPE,
	'DRUG' AS READ_CAT
FROM
	SAILUKHDV.READ_CD_CV2_SCD R
WHERE
	READ_CODE LIKE 'f1%'
	OR READ_CODE LIKE 'f2%'
	OR READ_CODE LIKE 'fw%'
UNION
--
--ORAL ANTIDIABETICS
SELECT
	R.READ_CODE,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC,
	'ANTIDIAB' AS READ_TYPE,
	'DRUG' AS READ_CAT
FROM
	SAILUKHDV.READ_CD_CV2_SCD R
WHERE
	READ_CODE LIKE 'f3%'
	OR READ_CODE LIKE 'f4%'
	OR READ_CODE LIKE 'ft%'
UNION
--
--NSAID
SELECT
	R.READ_CODE,
	CASE
		WHEN R.PREF_TERM_198 IS NULL AND R.PREF_TERM_60 IS NULL THEN R.PREF_TERM_30
		WHEN R.PREF_TERM_198 IS NULL THEN R.PREF_TERM_60
		ELSE PREF_TERM_198
	END AS DESC,
	'NSAID' AS READ_TYPE,
	'DRUG' AS READ_CAT
FROM
	SAILUKHDV.READ_CD_CV2_SCD R
WHERE
	READ_CODE LIKE 'j2%'
) 
; 
COMMIT;
--
------------------------------------------
--
-- Select all results
SELECT 
	* 
FROM 
	SAILW1483V.PHEN_DRUG_READ;
--
-- Count all results
SELECT 
	COUNT(*)
FROM 
	SAILW1483V.PHEN_DRUG_READ;
------------------------------------------

